experiment_name: zmef_MEFB
#data_path: /data_b/hxy/datasets/Lytro
#data_path: /data/datasets/SICE_single/
#data_path: /data/datasetsMEF/dataset_MEFopt/
#data_path: /data/datasets/MEFB_single/
data_path: /data/datasets/dataset_SICE/Test_2E/
#data_path: /data/datasets/ZMEF/matlab/results/
#data_path: /data/datasets/MEF/dataset_MEFB/
#data_path: /data/datasets/Real-MFF/
#data_path: /data/datasets/MFI-WHU/
dataset: MEF                  # [Lytro|Real-MFF|MFI-WHU|Lytro3]
save_path: ./results_SICE/
writer_path: ./run/

lr: 0.001
alpha: 20                       # [5|20]
beta: 0.05                      # [0.001|0.05]
rate: 1                         # [1|0.5]

num_iter: 500                  # 1500
img_size: [520, 520]            # [520, 520]
save_freq: 100
percep_freq: 100
rand_seed: 17
thresh: 600                     # 700
